### ISSUE TITLE
请问，flippy内核编译

### ISSUE THREAD

**Issue by hoyzhang** [w2xg2022/actions4ztebv310#1]
请问，flippy的内核，是来自这个吗？
`https://github.com/unifreq/linux-5.15.y`

还有，S905L3的固件，来自这个吗？具体怎么指定S903LB呢？
`云编译代码修改自https://github.com/ophub/amlogic-s9xxx-armbian/，特此感谢。`

谢谢！

**Comment by w2xg2022** [comment]
云编译代码是库里：https://github.com/w2xg2022/actions4ztebv310/blob/main/.github/workflows/build-armbian.yml
可以看33行指定了s905l3b-ip103h（它其实是s905l3b），165行指定了flippy。

这个BV310比较神奇，它是S905L3，但要用S905L3B的flippy内核才能U盘、emmc正常运行。
