### ISSUE TITLE
安卓包刷机卡2%

### ISSUE THREAD

**Issue by stonegitt** [w2xg2022/actions4ztebv310#2]
![image](https://github.com/w2xg2022/actions4ztebv310/assets/88572144/124bcf34-5a44-4b47-b772-ef73c00e0397)

**Comment by stonegitt** [comment]
其他的L3的包能刷进去，但是hdmi无显示输出。

**Comment by stonegitt** [comment]
猜测，你那个有可能是S905L2的CPU打的S905L3的标

**Comment by moli765** [comment]
和你一样的情况。请问后来刷入armbian了吗
